### ISSUE TITLE
Create ubos-admin subcommand that lists installable apps and accessories

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#11]
E.g.

```
ubos-admin listinstallables
ubos-admin listapps
ubos-admin listaccessories --for <app>
```

It would be most elegant to augment the package with some searchable fields, e.g. add to .PKGINFO:

```
type : app | accessory
app: <appid>
```

(like we do in ubos-manifest.json) but this would require:
- a change in makepkg to also generate those fields
- a change in pacman, to be able to search for those fields
- it may also require a change in repo-add
  This conflicts with the goal of not forking Arch code.

**Comment by jernst** [comment]
Actually this is not necessary. `pacman -Sl hl` does mostly the same.
