### ISSUE TITLE
Wrong app name ends "createsite" sequencer

### ISSUE THREAD

**Issue by ffatgit** [uboslinux/ubos-admin#210]
Version:
UBOS Beta8 (Virtual Box image)

Issue:
A typing mistake while the "createsite" sequence of a app name abort the hole sequence and have to start again from the beginning.
Circumstances of the issue:
Correct app name = webtrees
Mistake while typing = webtree

Solution:
Check of the existing app names. Message to user in fault situation and chance to repeat the app name input.
Same principle works with the "ubos-admin" commands; for example the "createsite" command it self.
Correct command name = createsite
Mistake while typing = createsit
Result = A fault message idicates the situation, and the input could repeat/change

**Comment by jernst** [comment]
These are two issues. The createsit/e is typical Unix behavior, we won't change this. However, we should loop around and let the user attempt to type the correct package instead of aborting.
