### ISSUE TITLE
Specify the data storage drive command

### ISSUE THREAD

**Issue by jeffkz** [uboslinux/ubos-admin#236]
Example like the nextcloud, i'm a bit confusing on how UBOS want it to work as originally I tested, the speed is really slow, and i have no idea how to set the cloud data to store on specify external HDD.

**Comment by jernst** [comment]
It's not clear to me what you are asking for. Are you asking for help with a particular installation? This is for bugs and perhaps feature requests, not support.

**Comment by jeffkz** [comment]
Installation request also should be added to feature.

I personal can't find a way to do that. Just some sort of feedback also.
