### ISSUE TITLE
Always create btrfs snapshot prior to upgrade

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#28]
Obviously only for btrfs partitions.

Perhaps in a structure similar to this: https://wiki.archlinux.org/index.php/Btrfs_-_Tips_and_tricks#Snapshots and/or perhaps using snapper per https://wiki.archlinux.org/index.php/Snapper#Pre-post_snapshots_with_pacman so there's automatic cleanup

**Comment by jernst** [comment]
For this, we should use `snapper`.

**Comment by jernst** [comment]
As a first step, per 5030b5a82ef6d9f50a293bc1f9a38ef2e31f5a4f snapper now gets pre-installed and pre-configured on btrfs volumes.

**Comment by jernst** [comment]
Given that snapper was misconfigured per https://github.com/uboslinux/ubos-admin/issues/195, let's hold off on this one more time.

**Comment by jernst** [comment]
Next thing to do here is to make sure snapper works.

**Comment by jernst** [comment]
Need #222 to be fixed first.
