### ISSUE TITLE
Create a 'backupinfo' command

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#3]
In addition to 'backup' and 'restore', there should be a command that takes a .ubos-backup file and displays some information about what it contained in the file. For example:
 * the site(s)
 * the app(s)
 * the date and time the backup was created
etc.

**Comment by jernst** [comment]
Added `backupinfo` subcommand in 6105c64f27fe054850ce6199efdea8cb30bd6288
