### ISSUE TITLE
create site fails when running ubos in nspawn container

### ISSUE THREAD

**Issue by klundry** [uboslinux/ubos-admin#329]
I'm trying the new Beta 12 images.  Forgive me if they are not yet ready for consumption.

After booting ubos in a container on Arch on either x86_64 PC or EspressoBIN I get an error when attempting to deploy any site with "ubos-admin createsite". I get a long list of these errors:

`...

cp: failed to clone '/srv/http/sites/s39babdd3620d32167bc2de6c5dbaf75ab08313fb/selfoss/public/win8-71-icon.png' from '/usr/share/selfoss/selfoss/public/win8-71-icon.png': Operation not supported

ERROR: Createsite failed.`

**Comment by jernst** [comment]
Just tried the same thing, and it works fine for me in an `x86_64` container and on actual PC hardware. My guess: your filesystem is something else than `btrfs`. (Now, admittedly, it should work on something other than `btrfs` but I don't usually test that...

**Comment by jernst** [comment]
To copy files, we now try to save space on file systems that support copy-on-write. So `cp` gets invoked with `--reflink=always` ... except that it should have been `--reflink=auto` so we silently fallback on the inefficient copy on non CoW filesystems, see https://github.com/uboslinux/ubos-admin/blob/2b0154b9fc7f1823aa70a12681fae70737d15d1d/ubos-perl-utils/vendor_perl/UBOS/Utils.pm#L559

**Comment by jernst** [comment]
See 42341fefa1d93d431130130f55c80b0d99442393.

**Comment by klundry** [comment]
You are correct, I'm not using btrfs.  Ok, thanks for the explanation.
