### ISSUE TITLE
404 errors trying to update any packages from depot.ubos.net

### ISSUE THREAD

**Issue by klundry** [uboslinux/ubos-admin#333]
`[root@ubos-container ~]# ubos-admin update
error: failed retrieving file 'hl.db' from depot.ubos.net : The requested URL returned error: 404
error: failed to update hl (unexpected error)
error: failed retrieving file 'os.db' from depot.ubos.net : The requested URL returned error: 404
error: failed to update os (unexpected error)
error: failed retrieving file 'tools.db' from depot.ubos.net : The requested URL returned error: 404
error: failed to update tools (unexpected error)
error: failed to synchronize any databases
error: failed to init transaction (unexpected error)
ERROR: Command failed: pacman -Sy --noconfirm
:: Synchronizing package databases...
ERROR: Command failed: pacman -S ubos-admin --noconfirm
warning: ubos-admin-0.236-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) ubos-admin-0.236-1

Total Download Size:   0.13 MiB
Total Installed Size:  0.67 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
error: failed retrieving file 'ubos-admin-0.236-1-any.pkg.tar.xz' from depot.ubos.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
No packages installed or upgraded.
`

**Comment by jernst** [comment]
Duh. This is embarrassing. Not too many people must be using EspressoBINs so far ... should be fixed now. If so, please close the bug.

**Comment by klundry** [comment]
Fixed.
