### ISSUE TITLE
gladiwashere deployment failed

### ISSUE THREAD

**Issue by lastdot** [uboslinux/ubos-admin#343]
deviceclass: ec2
test-ubos-yellow-x86_64-ec2.20171126-083021
id: 4.7.2.a

Note: testsite.json was not explicitly provided in the test instruction. I used "https://github.com/uboslinux/ubos-toyapps/blob/master/gladiwashere-python-mysql/testsite.json"
I hope that is correct.

Expected result: Successful deployment of gladiwashere.

Actual result (Terminal output):
cat testsite.json | ssh -i ubos-testing2.pem shepherd@54.88.134.12 sudo ubos-admin deploy --stdin -v
INFO : ubos-admin deploy --stdin -v
INFO : Installing prerequisites
ERROR: Failed to install package(s). Pacman says: error: target not found: gladiwashere-python

**Comment by jernst** [comment]
Good guess about `testsite.json`, but let's use this file instead that I just created: https://github.com/uboslinux/ubos-testing/blob/master/ubos/gladiwashere-python-mysql.json

First get the `ubos-admin update` workaround from #342 working. Then come back to this one. If it works, @lastdot please close this; if not, append the problem in the comments.

**Comment by lastdot** [comment]
gladiwashere deployment is now successful.
