### ISSUE TITLE
"grep context mattermost-noacc.json" returns empty value for "context"

### ISSUE THREAD

**Issue by lastdot** [uboslinux/ubos-admin#355]
deviceclass: ec2
test-ubos-apps-red-x86_64-ec2.20171208-231016
4.9.5.o
4.9.6.a

"grep context mattermost-noacc.json" returns empty value for "context".

**Comment by jernst** [comment]
This is fine. The script was attempting to say "grep may note produce a value, in which case don't do this step" but I guess it wasn't sufficiently clear.
