### ISSUE TITLE
error in deploying mediawiki with no accessories

### ISSUE THREAD

**Issue by lastdot** [uboslinux/ubos-admin#356]
deviceclass: ec2
test-ubos-apps-red-x86_64-ec2.20171208-231016
4.10.22.a

Terminal output:
sites[0]$ sed -e 's!testsite!ubostest.xyz!g' mediawiki-noacc.json | ssh -i ~/ubos-testing2.pem -l shepherd ubostest.xyz sudo ubos-admin deploy -v --stdin
INFO : ubos-admin deploy -v --stdin
ERROR: Site JSON: customizationpoint specified for non-installed installable mediawiki-ext-confirmaccount , installed: mediawiki
sites[0]$

**Comment by jernst** [comment]
Fixed in https://github.com/uboslinux/ubos-testing/commit/dca60d3e52601794dccb20299eb727854a18deb6
