### ISSUE TITLE
confirmaccount extension still present in mediawiki app

### ISSUE THREAD

**Issue by lastdot** [uboslinux/ubos-admin#357]
deviceclass: ec2
test-ubos-apps-red-x86_64-ec2.20171208-231016
4.10.26.o

confirmaccount extension still present in mediawiki app. Probably due to issue #356 .

**Comment by jernst** [comment]
@lastdot: Let's retest the Mediawiki portion.

**Comment by lastdot** [comment]
confirmaccount extension no longer present in mediawiki app as per requirement.
