### ISSUE TITLE
Testing of functionality of docroot not done

### ISSUE THREAD

**Issue by lastdot** [uboslinux/ubos-admin#358]
I tried testing docroot with a sample "hello.html" file assuming that these are the right instructions:
https://ubos.net/docs/users/apps/docroot.html

What I tried:
626  rsync -rtlvH --delete-after --delay-updates --safe-links -e 'ssh -i ubos-testing2.pem' hello.html docroot@ubostest.xyz:a62adf55617cfe3311994444f17243e1d5dce8134/
  631  rsync -rtlvH --delete-after --delay-updates --safe-links -e 'ssh -i ubos-testing2.pem -l shepherd' hello.html docroot@ubostest.xyz:a62adf55617cfe3311994444f17243e1d5dce8134/
  632  rsync -rtlvH --delete-after --delay-updates --safe-links -e 'ssh -i ubos-testing2.pem -l shepherd' hello.html admin@ubostest.xyz:a62adf55617cfe3311994444f17243e1d5dce8134/
  634  rsync -rtlvH --delete-after --delay-updates --safe-links -e 'ssh -i ubos-testing2.pem' hello.html admin@ubostest.xyz:a62adf55617cfe3311994444f17243e1d5dce8134/

The supplied password for login does not work.

**Comment by jernst** [comment]
This is the wrong ssh key. Use `ssh -i ssh/id_rsa` (checked into git, for testing only) instead of `ssh -i ubos-testing2.pem`. There should be no password.

**Comment by lastdot** [comment]
Testing of functionality of "docroot" app successfully done.
