### ISSUE TITLE
ubos-install should have a parameter to create a swap partition

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#36]
btrfs does not support swap files, and we should allow the user to use a partition as swap. extend ubos-install to create a swap partition.

**Comment by indiebox** [comment]
Actually that should have a good default. E.g. if installing on drive(s) that are non-removable, create swap. Check

    /sys/block/sdX/removable

**Comment by jernst** [comment]
Add `--swappartition <partition>` to command-line arguments.
