### ISSUE TITLE
ubos-admin createsite unable to fetch mattermost

### ISSUE THREAD

**Issue by Hibryda** [uboslinux/ubos-admin#365]
Platform - espressobin.
Error: Pacman says: error: target not found: mattermost
Likely repo issue.

**Comment by jernst** [comment]
Sorry: We are using Mattermost's binaries (https://about.mattermost.com/download/) and they don't build for anything other than x86_64. So no Mattermost on UBOS on ARM.

**Comment by Hibryda** [comment]
Ah, good to know. Pity.

**Comment by Hibryda** [comment]
Can't see mention about it in docs though. Are there any other apps with same issue?

**Comment by jernst** [comment]
We are trying to stay out of attempting to port apps that their own developers haven't ported. There's plenty of UBOS-specific work that comes first ... 

If you look at the files here: https://github.com/uboslinux/ubos-buildconfig/tree/master/hl/us you can see which archs they are packaged for. If something doesn't say anything, it is for all architectures, which is almost all of them.

**Comment by Hibryda** [comment]
Ok. I understand your approach. How about plans for further apps? Is there a list of them?

**Comment by jernst** [comment]
There is a long list that people want: https://github.com/uboslinux/apps-wanted/issues

Personally I want to see Mastodon soon, and OpenHAB.

**Comment by Hibryda** [comment]
Thanks. Would back GitLab.

**Comment by jernst** [comment]
"back"? As in crowdfund? Or ...? I agree Gitlab would be nice.
