### ISSUE TITLE
Cannot install Nextcloud on AWS instance of UBOS

### ISSUE THREAD

**Issue by giltwist** [uboslinux/ubos-admin#399]
Just downloaded everything and installed it today.  Ran `sudo ubos-admin createsite --tls --letsencrypt`  and got all the way to the point where you specify an app, got the following error trying to install nextcloud:

> ERROR: Failed to install package(s). Pacman says: error: failed retrieving file 'nextcloud-12.0.0-1-any.pkg.tar.xz' from depot.ubos.net : The requested URL returned error: 404

**Comment by jernst** [comment]
Chances are you did not execute ``ubos-admin update`` recently.

**Comment by giltwist** [comment]
That worked.  You may want to update your video tutorial, which skips the `sudo ubos-admin update` step.

**Comment by jernst** [comment]
Ahh ... good point. The video hasn't been updated in a while ...
