### ISSUE TITLE
When there's a kernel update, reboot device as part of ubos-admin update

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#43]

**Comment by indiebox** [comment]
The way to do that might be this: during `ubos-admin update`, after the `pacman -S` (but not `-U`), check whether `uname -r` is the same version as the installed kernel package. If not the same, keep the backups where they are, reboot, and trigger update-step2 as part of the `systemctl start ubos-admin` activation.

Determining the installed kernel package might be a bit tricky, as the package names are different in particular on ARM.
