### ISSUE TITLE
Restore fails to recover letsencrypt-secured site.

### ISSUE THREAD

**Issue by adrianblakey** [uboslinux/ubos-admin#445]
A backup I took prior to unsuccessfully applying Beta 13 fails to recover my one and only Wordpress site that was secured by letsencrypt.

When running the restore it emits the following messages:

Obtaining letsencrypt certificate for site www.blakey.org ( s37... )
Failed to create directory /ubos/http/wellknown/s37 …
Obtaining certificate from letsencrypt failed. proceeding without certificate or TLS/SSL.
Make sure you are not running this behind a firewall, and that DNS is set up properly.

Of course the issue could reside in the backup ...

My pi is hiding behind my router which forwards ports 80 and 443 to the pi on the local network. The router uses dyndns to map my domain to the dhcp-supplied Inet address, and letsencrypt was working just fine before the restore.

I took the backup then tried to apply the Beta 13 - that failed. This might be because I was not up-to-date on updates. After trying to get the Beta 13 update to work by deleting several files it was complaining about I gave up and re-installed Ubos, and then applied the backup.

I am hesitant to attach the backup, but if it would help to resolve this I can supply it out of band.

**Comment by jernst** [comment]
Hmm, I'm not quite seeing this problem in the code ... could you post the output of the following:
1. `pacman -Qi ubos-admin`
2. `cat /etc/ubos/config.json`
3. `ubos-admin restore --in <backup> -v -v` (or whichever way you invoke the restore, just give it two `-v`'s)

**Comment by adrianblakey** [comment]
[typescript.zip](https://github.com/uboslinux/ubos-admin/files/2020419/typescript.zip)

Here the result ...

**Comment by jernst** [comment]
Ah! That helped. Turns out we doing an `mkdir` instead of an `mkdir -p` and so the parent directory isn't there when it's needed for the Letsencrypt dance.

Workaround: Before restoring, as root, `mkdir -p /ubos/http/wellknown/`.
