### ISSUE TITLE
Createsite fails

### ISSUE THREAD

**Issue by adrianblakey** [uboslinux/ubos-admin#506]
The lastest install has an issue.

Downloaded ubos_yellow_armv7h-rpi2_LATEST.img

Booted up and tried to create a site.

...
First app to run (or leave empty when no more apps): wordpress
App wordpress suggests context path /blog
Enter context path: /blog
Any accessories for wordpress? Enter list: 
Next app to run (or leave empty when no more apps): 
Downloading packages...
ERROR: Failed to install package(s): certbot-apache php-gd. Pacman says: warning: cannot resolve "python-requests-toolbelt", a dependency of "python-acme"
warning: cannot resolve "python-acme=0.26.1", a dependency of "certbot"
warning: cannot resolve "certbot=0.26.1", a dependency of "certbot-apache"
warning: cannot resolve "python-requests-toolbelt", a dependency of "python-acme"
warning: cannot resolve "python-acme=0.26.1", a dependency of "certbot-apache"
error: failed to prepare transaction (could not satisfy dependencies)

Note: same errors trying to restore a backup file too ...

**Comment by jernst** [comment]
Confirmed. That package is missing on ARM. Well, was, because I just added it :-). Try again after updating:

[code]
sudo ubos-admin update
sudo pacman -S certbot
[/code]

If it works, please tag this issue as "verified" and close. Thanks.,
