### ISSUE TITLE
Createsite fails with an invalid line in the conf file

### ISSUE THREAD

**Issue by adrianblakey** [uboslinux/ubos-admin#507]
Easiest way is to attach the screen shots - however I am unable to drop files into this ...

I ran ubos-admin createsite --tls --letsencrypt

It creates a conf file that has an invalid line 31.

"Invalid command 'SSLEngine', perhaps misspelled or defined by a module not included in the server configuration.

Line 31: 

SSLEngine on

**Comment by jernst** [comment]
It seems I need to set a Pi up with a public IP address ... not a scenario that I typically test, which is why you are running into those letsencrypt-related problems on ARM. It works on EC2 :-)

**Comment by adrianblakey** [comment]
ty

Adrian Blakey
adrianblakey@gmail.com
Skype: adrianblakey
(510) 747-8057

**Comment by jernst** [comment]
I cannot reproduce this. I just:
* installed UBOS yellow on a RPi2
* setup pagekite
* created a site without TLS (this is needed to work around #509)
* redeployed the site with TLS / letsencrypt

The site came up just fine with TLS.

I realize your setup doesn't use pagekite, but there is no reason I can see why that should have any impact.

The error you have implies that the Apache module `mod_ssl` hadn't been activated yet. Could you:
* restart Apache with `sudo systemctl restart httpd`
* try again, and if this fails:
* post the content of `/etc/httpd/mods-enabled/`

**Comment by adrianblakey** [comment]
Catch 22. No httpd running so I can't create anything.

I believe you are seeing something different because I applied a backup
before trying createsite.

My process:

1. Burn an image.
2. Insert into pi
3. Start system
4. ubos-admin restore
5. createsite

Backup file: https://www.dropbox.com/s/b7j258y4ms4jscl/2018-5-13-backup?dl=0

Adrian Blakey
adrianblakey@gmail.com
Skype: adrianblakey
(510) 747-8057

**Comment by adrianblakey** [comment]
Just for grins I went back and started with a clean image and tried again.

I tried to create a site with no applications i.e. I left the apps empty.

ubos-admin createsite --tls --letsencrypt

It failed with:

jobs for iptables failed because control process exited with error code.

Job for httpd.service failed

**Comment by jernst** [comment]
These are not consistent error messages, aka the errors you are seeing aren't consistently reproduceable. In any case, I need specific error messages, e.g. look for them with `sudo journalctl --since -5m` or whatever the right time constant might be.

Also, with `createsite`, what's the app you are trying to set up.

Also, how exactly is your RPi connected to the public internet?

**Comment by adrianblakey** [comment]
I attached the journal to the last email - I am guessing you are not
receiving it. I'll try again ...

I think that's exactly the issue - I am not trying to create a site with an
app at all. I leave the answer prompt blank.

Connection: Pi <- home lan 172 ...-> router, NAT port 80/443 open and
forwarded to pi <--comcast--> the world modem/bridge -->

-- The start-up result is RESULT.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Successfully called
chroot().
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Successfully dropped
remaining capabilities.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Loading service file
/services/http.service.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Loading service file
/services/https.service.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Network interface
enumeration completed.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Server startup
complete. Host name is ubos-raspberry-pi2.local. Local service cookie is
3633725144.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Service "UBOS secure
web apps at ubos-raspberry-pi2" (/services/https.service) successfully
established.
Oct 06 00:40:07 ubos-raspberry-pi2 avahi-daemon[1759]: Service "UBOS web
apps at ubos-raspberry-pi2" (/services/http.service) successfully
established.
Oct 06 00:40:07 ubos-raspberry-pi2 iptables-restore[1763]: Another app is
currently holding the xtables lock. Perhaps you want to use the -w option?
Oct 06 00:40:07 ubos-raspberry-pi2 systemd[1]: iptables.service: Main
process exited, code=exited, status=4/NOPERMISSION
Oct 06 00:40:07 ubos-raspberry-pi2 systemd[1]: iptables.service: Failed
with result 'exit-code'.
Oct 06 00:40:07 ubos-raspberry-pi2 systemd[1]: Failed to start Packet
Filtering Framework.
-- Subject: Unit iptables.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit iptables.service has failed.
-- 

-- The start-up result is RESULT.
Oct 06 00:40:08 ubos-raspberry-pi2 systemd-networkd[1761]: Could not set
hostname: The name org.freedesktop.PolicyKit1 was not provided by any
.service files
Oct 06 00:40:08 ubos-raspberry-pi2 httpd[1771]: AH00526: Syntax error on
line 31 of /etc/httpd/sites/s8d713d2e82df1135cbbcbf5f3b41eec3bd69b5b5.conf:
Oct 06 00:40:08 ubos-raspberry-pi2 httpd[1771]: Invalid command
'SSLEngine', perhaps misspelled or defined by a module not included in the
server configuration
Oct 06 00:40:08 ubos-raspberry-pi2 systemd[1]: httpd.service: Control
process exited, code=exited status=1
Oct 06 00:40:09 ubos-raspberry-pi2 httpd[1772]: Stopping httpd.service
Oct 06 00:40:09 ubos-raspberry-pi2 systemd[1]: httpd.service: Failed with
result 'exit-code'.
Oct 06 00:40:09 ubos-raspberry-pi2 systemd[1]: Reload failed for Apache Web
Server configured for UBOS.
-- Subject: Unit httpd.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-

**Comment by jernst** [comment]
This seems related to #509.

**Comment by jernst** [comment]
Likely because the created site was empty, per #496.

**Comment by jernst** [comment]
This seems to be working now. To be promoted to `yellow` and `green` shortly.
