### ISSUE TITLE
On AWS instance sudo ubos-admin update gives error "Required service httpd has failed."

### ISSUE THREAD

**Issue by giltwist** [uboslinux/ubos-admin#575]
Just doing a typical semi-annual update.    Everything was running fine from last update about 6 months ago, just looking to get the latest security updates and whatnot.  Update started to work, and I saw a bunch of things start to update, then I got kicked off my putty connection and my nextcloud site went down.  When I logged back in, I attempted to do sudo ubos-admin update again and received the error "Required service httpd has failed. Attempting to restart. Try invoking your command again in a little while."  Waited. Retried.  Same error.  Did pacman -Su ubos-admin.  An update was installed.  Retried. Same error.  Rebooted instance.  Same error.

**Comment by jernst** [comment]
This may be easier to discuss on the forum: https://forum.ubos.net/ . Could you post your site json (e.g. `sudo ubos-admin showsite -s s... --json`) -- replacing whatever confidential information (e.g. admin password, SSH keys, ...) before you post.

**Comment by giltwist** [comment]
I would love to do that, but running the command you suggested ALSO causes the httpd error.

**Comment by jernst** [comment]
It doesn't emit anything? In which case, let's do it the slow way:
* What's your hostname?
* Are you running http or https, and if so, letsencrypt or not?
* `cat /etc/ubos/channel`
* `cat /ubos/lib/ubos/sites/*-full.json` (please sanitize)
* `sudo systemctl status httpd`
* `sudo apachectl configtest`

**Comment by giltwist** [comment]
>What's your hostname?

intranet.paragon-tec.com running on an AWS t2.medium 

>Are you running http or https, and if so, letsencrypt or not?

https and I used the let's encrypt automated thing when I deployed the site many months ago, possibly even over a year.

> cat /etc/ubos/channel

yellow

> cat /ubos/lib/ubos/sites/*-full.json

Permission denied.  Tried to sudo but it asks for a password for shepherd which I've never needed for sudo ubos-admin.  I log in with a public key normally.

> sudo systemctl status httpd
`
httpd.service - Apache Web Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-02-22 19:49:44 UTC; 27min ago
  Process: 2157 ExecStopPost=/usr/share/ubos-admin/bin/ubos-service-poststop httpd (code=exited, status=0/SUCCESS)
  Process: 2152 ExecStart=/usr/bin/httpd -k start -DFOREGROUND (code=exited, status=1/FAILURE)
  Process: 2151 ExecStartPre=/usr/bin/perl -MUBOS::Apache2 -e UBOS::Apache2::ensureConfigFiles(); (code=exited, status=0/SUCCESS)
  Process: 2136 ExecStartPre=/usr/share/ubos-admin/bin/ubos-service-prestart httpd (code=exited, status=0/SUCCESS)
 Main PID: 2152 (code=exited, status=1/FAILURE)

Feb 22 19:49:44 ubos-ec2 systemd[1]: Starting Apache Web Server...
Feb 22 19:49:44 ubos-ec2 httpd[2136]: Starting httpd.service
Feb 22 19:49:44 ubos-ec2 systemd[1]: Started Apache Web Server.
Feb 22 19:49:44 ubos-ec2 httpd[2152]: AH00526: Syntax error on line 33 of /etc/httpd/sites/sb4aa20e2f8f329201c4cdeb8dab0654cc33d3ad8.conf:
Feb 22 19:49:44 ubos-ec2 httpd[2152]: SSLCertificateKeyFile: file '/etc/httpd/ssl/sb4aa20e2f8f329201c4cdeb8dab0654cc33d3ad8.key' does not exist or is empty
Feb 22 19:49:44 ubos-ec2 systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 19:49:44 ubos-ec2 httpd[2157]: Stopping httpd.service
Feb 22 19:49:44 ubos-ec2 systemd[1]: httpd.service: Failed with result 'exit-code'.
`
> sudo apachectl configtest

Again asks for a password that I don't know.

**Comment by jernst** [comment]
Sorry, my bad about the permissions. This looks like it's related to some issue we've been related to letsencrypt although it's unclear why this would have happened during an upgrade. The good news is that this code has been rewritten and it going to be in the next update, which is due shortly. The not so good news is that it isn't out yet, and I don't know how painless the upgrade will be given the state of your instance. (hard to test for that one!)

If this were a server I maintain, this is what I'd do:
* temporarily redeploy the site without letsencrypt, using an (edited) version of the current Site JSON [1]. This should work without issues, except that maybe the httpd error is printed a few more times, but harmless.
* then deploy with letsencrypt, putting the letsencrypt tag back into the Site JSON first. 

Hope this helps.

[1] https://ubos.net/docs/developers/site-json.html

**Comment by giltwist** [comment]
> letsencrypt although it's unclear why this would have happened during an upgrade.

Is it possible the newer version is looking for the key in a different folder than the old version?  I have a box that runs Mopidy that had a similar problem where the config file location changed between versions.  I would like to run `sudo find / -name "*.key" ` to test this theory but hit the same sudo permission issue.  I would recommend that `find` be added to your list of allowed sudo commands like sudo ubos-admin is.

> temporarily redeploy the site without letsencrypt

As in backup, undeploy, deploy, then restore backup?

**Comment by jernst** [comment]
Backup is always a good idea. Simply deploying the Site JSON without the "tls" entry should be sufficient.
Also see https://ubos.net/docs/users/faq.html#i-need-root

**Comment by giltwist** [comment]
Ah! Thank you.  That FAQ helped.  Some additional details now:

- `sudo ubos-admin backup` also issues the httpd error, as does status, listsites, and even createsite
- `apachectl configtest` confirms that the issue is a missing .key file with the same name as my siteid specified in *-full.json
- running `find / -name "*.key"` reveals that the above .key file is nowhere to be found.

**Comment by giltwist** [comment]
Some updates and a thought.

**Updates:**

* I commented out the ssl lines in /etc/httpd/sites/$siteid.conf, restarted httpd and my site is back up...albeit with firefox complaining about the self-signed certificate and ubos-admin commands are responsive again.
* I attempted to `sudo ubos-admin backup --out~/all-$(date +%Y%m%d%H%M).ubos-backup` as per the wiki and got an invocation error.  Apparently my version wants --backuptofile not --out
* Anyway, ran that and got an httpd.service reload failure error.  A quick check shows that the $siteid.conf had been overwritten by the backup.
* removed the tls section from /ubos/lib/ubos/sites/*-full.json, fixed the conf and httpd service again, then backup ran correctly
* Redeploying with TLS/LE removed successful.  Re-redeploying with TL/LE restored failed.
* A quick check shows that /etc/httpd/ssl/$siteId.key is still not present.

Where is the $siteId.key made originally?  If I can look at that, I can regenerate the missing file manually.

**Comment by jernst** [comment]
Let's separate this discussion into two pieces:
* Is there a reproduceable bug in UBOS? If so, please post steps to reproduce. If not, let's close this ticket.
* how to recover the installation you have. This is better discussed on the UBOS forum at https://forum.ubos.net/

Re keys: they either come from what you specified in `createsite` or from Letsencrypt. Note that once you step out of the "sandbox" provided by the privileges of the `shepherd` user (without becoming root), UBOS (and me!) can't help you any more because the system is in a state that nobody has ever seen and cannot automatically recover.

**Comment by giltwist** [comment]
Alright.  Moving to forum.
