### ISSUE TITLE
ubos-admin restore failed at Amazonses password

### ISSUE THREAD

**Issue by Hagnkerchief** [uboslinux/ubos-admin#599]
**Device** AWS EC2 Instance with amazonses and wordpress site

Ran two different backups before hand, one via ubos-admin backup and the other via ubos-admin undeploy ... --backup

A ubos-admin restore from either fail with:
ERROR: Cannot find symbol installable.customizationpoints.aws_secret_key.value

**Comment by jernst** [comment]
This one is new as far as I know. `yellow` channel? Last update made approx when?

Can you look inside the backup file and see whether the values are there? (in other words: is the problem when the backup is being created, or when it is being restored)

**Comment by Hagnkerchief** [comment]
Just started the instance today, ubos-yellow-20190227-1 (ami-0bd18d0ebd2745237)

Neither backup of the amazonses.json file in installables have "value" defined for aws_access_key_id or aws_secret_key.

However, the appconfigs JSON for amazonses contains the proper information.

Could it be as simple as adding a default value like the ses_mail_server?

**Comment by Hagnkerchief** [comment]
Bigger brain thought, what if the restore is failing cause its missing an "s" at the end of installable. So it should be getting the password from installables.customizationpoints.aws_secret_key.value

**Comment by jernst** [comment]
Trying to reproduce, but no success. This is what I did:
* Create new EC2 `yellow` instance by following the wizard from https://ubos.net/quickstart/
* Set up DNS A record mapping to the instance's public IPv4 address
* ssh as shepherd
* `sudo ubos-admin update`
* `sudo ubos-admin createsite`. Hostname same as DNS name above. Enter `amazonses` as first app, and `wordpress` as the second, with no further customization. Wordpress is at root of site. Suitable SES keys.
* Accessed Wordpress with web browser. Logged on. Created blog post.
* `sudo ubos-admin backup --backuptofile file.ubos-backup`
* `sudo ubos-admin undeploy -a`
* Verified that site is gone, and files in `/etc/amazonses` are empty
* `sudo ubos-admin restore --in file.ubos-backup`
* Site is back, blog post is back, and files `/etc/amazonses/*map` have the SES credential info in them.

@Hagnkerchief where is this different for you?

**Comment by Hagnkerchief** [comment]
On the site that didn't restore I had used the indieweb customization options for wordpress. I had also run the install for amazonS3 backups but I don't think I used it at all.

Can't think of anything else different at the moment.

**Comment by jernst** [comment]
Well, I need an example that I can reproduce to be able to analyze and/or suggest a remedy :-) 

Wordpress plugins should not get in the way of amazonses, nor should amazons3.

**Comment by jernst** [comment]
Not reproduceable. Closing.
