### ISSUE TITLE
Letsencryt problem

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-admin#618]
1. Brand-new EC2 server
1. Create site `www.example.com` with letsencrypt and some apps
1. Redeploy `www.example.com` to `example.com`
1. Create new site `www.example.com` with `redirect` at the root
produces:
```
Mar 31 20:09:48 ubos-ec2 httpd[5445]: AH00526: Syntax error on line 33 of /etc/httpd/sites/s04eeceff28404628c7ad9c3061fe88c66d22f16b.conf:
Mar 31 20:09:48 ubos-ec2 httpd[5445]: SSLCertificateKeyFile: file '/etc/httpd/ssl/s04eeceff28404628c7ad9c3061fe88c66d22f16b.key' does not exist or is empty
```
It may be simpler than this, but this is the transcript.

**Comment by moretocome** [comment]
I have been seeing this issue, @jernst  ever since my first letsencrypt renewal. It seems like certificates are not properly copied from the appropriate ```letsencrypt/archive``` folder to ```/etc/httpd/ssl``` folder.

Now ```sudo ubos-admin backup --backuptodirectory ~``` throws the following errors (but seems to complete):
```
[shepherd@[host] ~]$ sudo ubos-admin backup --backuptodirectory ~
WARN : Undefined content (usually programming error) when attempting to save file /etc/httpd/ssl/[site ID].key
WARN : Undefined content (usually programming error) when attempting to save file /etc/httpd/ssl/[site ID].crt
ERROR: httpd.service reload failed: Job for httpd.service failed because the control process exited with error code.
See "systemctl status httpd.service" and "journalctl -xe" for details.
```
Now I have to manually switch to the root user and issue ```cp /etc/letsencrypt/archive/[host URL]/fullchain3.pem /etc/httpd/ssl/[site ID].crt && cp /etc/letsencrypt/archive/[host URL]/privkey3.pem /etc/httpd/ssl/[site ID].key && chown root:http /etc/httpd/ssl/[site ID].crt && chmod 0660 /etc/httpd/ssl/[site ID].crt && chown root:http /etc/httpd/ssl/[site ID].key && chmod 0660 /etc/httpd/ssl/[site ID].key && systemctl restart httpd``` to get the site back in operation.

**Comment by jernst** [comment]
Indeed, there have been some renewal-related issues. Sorry about that. It's really hard to test renewal because renewal happens so infrequently.

Fortunately, much of the Letsencrypt integration code was rewritten recently. It should now do renewal correctly, as well as device migration, and we have been testing against a patched local version of [pebble](https://github.com/letsencrypt/pebble). I expect that code to show up on the `red` release channel later today, and depending on how testing goes, on `yellow` in a few days.
