### ISSUE TITLE
Update of tomcat7 applications seem flaky

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#69]
Experience:
1. Update device running jenkins
2. On x86_64, everything fine
3. On arm6 & arm7, 404 results
4. Restarting services did not change anything
5. rm -rf /etc/tomcat7/ubos/sites-apps/siteid/ROOT and restarting tomcat7 fixes it

**Comment by jernst** [comment]
This should be working, as update removes the Site, and that triggers a delete of /etc/tomcat7/ubos/sites-apps/siteid. Perhaps there's a timing issue on ARM?

**Comment by jernst** [comment]
Jenkins on those arm devices simply doesn't work reliably, due to timeouts. Removed jenkins package from those platforms.
