### ISSUE TITLE
createsite fails to install nextcloud

### ISSUE THREAD

**Issue by louisdorard** [uboslinux/ubos-admin#750]
`ubos-admin createsite` fails after specifying `nextcloud` when prompted "First app to run". The error message is "ERROR: Failed to install package(s): nextcloud. Pacman says: error: target not found: nextcloud".

I tried `ubos-admin update` but got "No packages installed or upgraded."

I tried `pacman -S nextcloud` but got "error: target not found: nextcloud"

I'm using ubos on raspberry pi 1. I downloaded and wrote ubos_yellow_armv6h-rpi_LATEST.img on the pi's SD card on July 16, 2020.

**Comment by jernst** [comment]
Nextcloud has become too resource-consuming to run on the Pi 1 and similar devices. So we don't build it for ``armv6h`` any more because there is no point. Here is the JSON that defines what architecture gets which apps: https://github.com/uboslinux/ubos-buildconfig/tree/master/hl/us

**Comment by louisdorard** [comment]
Thanks for your reply @jernst! I feel like this should be explained in the UBOS documentation. Unfortunately I don't have sufficient technical knowledge in this area to understand the contents of the directory you shared...

On my way to order a brand new Pi 4!

**Comment by jernst** [comment]
Yea, we should include this in the text documentation. There isn't a good way of automating this right now, which why it hasn't happened. Re Pi4, the next UBOS update will support the Pi4 (fingers crossed), but it hasn't been released yet. Just to warn you :-)

**Comment by louisdorard** [comment]
OK! Thanks for the warning Johannes!
