### ISSUE TITLE
Failed tor site creation leaves back invalid hostname

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-admin#775]
Which then gets in the way of listsites (`-not-assigned-yet`).

**Comment by jernst** [comment]
There seem to be some other Tor related issues as well: `createsite -n` and then `deploy` has issues recognizing the JSON because there is no `hostname` file.

**Comment by ralphshinevar** [comment]
Hello, I tried to create a tor site.  The Tor process timed out, now when I listsites I get this:  ERROR: Site JSON: invalid hostname, is: -not-assigned-yet  How to fix?

**Comment by jernst** [comment]
Seems to work now.
