### ISSUE TITLE
[SOLVED] pi4 ubos-update fails with 403 on avahi+0 

### ISSUE THREAD

**Issue by teledyn** [uboslinux/ubos-admin#884]
This is using the current xz image, ubos-update and pacman -Syu both respond with

error: failed retrieving file 'avahi-0.8+22+gfd482a7-3-armv7h.pkg.tar.xz' from depot.ubos.net : The requested URL returned error: 403
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

**Comment by jernst** [comment]
We host those package files on Amazon S3. Their HTTP API appears to have a recent regression where it does not accept URLs that contain a `+` in the path any more (although the URL spec says that's perfectly legal) and requires a `%` escape for the `+` instead.

We have a workaround, but it isn't in the repos yet. https://github.com/uboslinux/ubos-admin/commit/90fa9318c992270f82a7a579d7df5347049af24cb .

**Comment by teledyn** [comment]
that commit link was a 404 - is this something I could fix manually?

**Comment by jernst** [comment]
Copy-paste error, sorry, link fixed. Before it shows up in the repos, you could:

* `makepkg` and `sudo pacman -U` the three affected packages (see commit) yourself
* `curl -O http://depot.ubos.net/green/armv7h/os/avahi-0.8%2B22%2Bgfd482a7-3-armv7h.pkg.tar.xz` and same with the associated `.sig` file, and install with `sudo pacman -U`.

**Comment by teledyn** [comment]
Excellent, thanks!

**Comment by teledyn** [comment]
This gets me further, but now a new problem related to the repository? It fails whether I say y or n.

error: archlinux-keyring: signature from "Christian Hesse <eworm@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/archlinux-keyring-20230504-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

**Comment by jernst** [comment]
https://ubos.net/docs/administrators/faq-howto-troubleshooting/error-corrupted-package/
