### ISSUE TITLE
Create a ubos-dhcpcd.service

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-admin#9]
And start that one instead of dhcpcd.service. That allows us to use our own version of /etc/dhcpcd.conf and overwrite it as we like with setnetconfig, without getting a /etc/dhcpcd.conf.new when upgrading.

**Comment by indiebox** [comment]
There is a question whether we should use systemd-networkd instead.

**Comment by jernst** [comment]
Currently, setnetconfig overwrites dhpcd.conf, so an upgrade of dhcpcd produces /etc/dhcpcd.conf.pacnew, which we then blame the user for :-)

**Comment by jernst** [comment]
This is obsolete, because we now use systemd-networkd for all networking.
